const {test, expect} = require('@playwright/test');

test('Take Screenshot_Element', async ({ page }, testInfo) => {
    await page.goto('https://www.wikipedia.org/');
    await expect(page).toHaveTitle(/Wikipedia/);

    //const searchBox = page.getByRole('searchbox');
    const searchBox = page.getByRole('searchbox', { name: 'search' });

    // await searchBox.screenshot({ path: testInfo.outputPath('searchbox.png') });
    //storing the screenshot with dynamic name using date and time method
   
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-'); // Replace colons and dots for filename
    const screenshotPath = `screenshots/searchbox_${timestamp}.png`;
    await searchBox.screenshot({ path: screenshotPath });
    console.log(`Screenshot saved at: ${screenshotPath}`);

    // //unique screenshot name for each test run in screenshots folder using Date.now() method
    // const screenshotPath2 = `screenshots/searchbox_${Date.now()}.png`;

    // await page.screenshot({ path: screenshotPath2 });
    // console.log(`Screenshot saved at: ${screenshotPath2}`);
});

test('Take Screenshot_TestTitle', async ({ page }, testInfo) => {
    await page.goto('https://www.wikipedia.org/');
    await expect(page).toHaveTitle(/Wikipedia/);
    // // Take a screenshot of the entire page with dynamic name using test title and timestamp
    // const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    // const screenshotPath = `screenshots/${testInfo.title.replace(/\s+/g, '_')}_${timestamp}.png`;
    // await page.screenshot({ path: screenshotPath });
    // console.log(`Screenshot saved at: ${screenshotPath}`);

    //mention screenshot name as <testname>_ in screenshots folder for demo purpose
    const screenshotName = `screenshots/${testInfo.title}-${Date.now()}.png`;
    await page.screenshot({ path: screenshotName });
    console.log(`Screenshot saved at: ${screenshotName}`);
/*
Notes:
- The first test captures a screenshot of the search box element with a unique name based on the current timestamp.
- The second test captures a screenshot of the entire page, naming the file based on the test title and timestamp for better organization.
- Ensure that the 'screenshots' directory exists before running these tests, or Playwright will throw an error.
- Screenshots are useful for debugging and visual validation of test results.
- To run these tests, use the command:
    npx playwright test tests/06_screenshots/01_screenshot.spec.js --headed
- This will allow you to see the browser actions and verify that screenshots are taken correctly.
- You can also view the screenshots after the test execution to confirm they were captured as expected.
*/
});

test('Take Screenshot_BestPractice', async ({ page }, testInfo) => {
    await page.goto('https://www.wikipedia.org/');
    await expect(page).toHaveTitle(/Wikipedia/);

    //We had screenshots folder for demo purpose
    // Best [ractice is to save screenshots in test-results folder which is generated by Playwright after test execution using testInfo.outputPath() method
    
    await page.screenshot({path: testInfo.outputPath('Wikipedia_success.png')});
    console.log(`Screenshot saved at: ${testInfo.outputPath('Wikipedia_success.png')}`);
/*Notes:
- This test demonstrates the best practice of saving screenshots in the 'test-results' folder generated by Playwright after test execution.
- The screenshot is named 'Wikipedia_success.png' and is stored in a path that includes the test title and timestamp for better organization.
- Using testInfo.outputPath() ensures that screenshots are saved in the appropriate location for each test run, making it easier to manage and review results.
- To run this test, use the command:
    npx playwright test tests/06_screenshots/01_screenshot.spec.js --headed
- After execution, you can find the screenshot in the 'test-results' folder with a name that includes the test title and timestamp.
*/
});

test('Take Screenshot_Element_BestPractice', async ({ page }, testInfo) => {
    await page.goto('https://www.wikipedia.org/');
    await expect(page).toHaveTitle(/Wikipedia/); 
    const searchBox = page.getByRole('searchbox', { name: 'search' });
    await searchBox.screenshot({ path: testInfo.outputPath('searchbox_element.png') });
    console.log(`Screenshot saved at: ${testInfo.outputPath('searchbox_element.png')}`);
/*Notes:
- This test captures a screenshot of the search box element and saves it in the 'test-results' folder using the best practice of utilizing testInfo.outputPath() for dynamic naming.
- The screenshot is named 'searchbox_element.png' and is stored in a path that includes the test title and timestamp for better organization.   
- Using testInfo.outputPath() ensures that screenshots are saved in the appropriate location for each test run, making it easier to manage and review results.
*/
});

test('Take Screenshot_BestPractice_with_UniqueName', async ({ page }, testInfo) => {
    await page.goto('https://www.wikipedia.org/');
    await expect(page).toHaveTitle(/Wikipedia/);

    //use Datenow() method to generate unique name for each test run
    const screenshotName = `Wikipedia_success_${Date.now()}.png`;
    await page.screenshot({ path: testInfo.outputPath(screenshotName) });
    console.log(`Screenshot saved at: ${testInfo.outputPath(screenshotName)}`);
});